version: '3'

services:
  store:
    # Dockerfile path like ./ or . or ./Dockerfile
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
